import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import Navbar from '@/components/shared/Navbar';
import "./globals.css";

const fontSans = Urbanist({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.className} antialiased`}
      >
        <Navbar />
        <main className="max-w-[1200px] min-h-screen container px-3 mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
